### ISSUE TITLE
Cannot read property 'acequire' of undefined 

### ISSUE THREAD

**Issue by nicholasareed** [securingsincity/react-ace#179] opened 2017-03-08 01:10 UTC
Any idea what causes this? I'm trying to use react-ace in a larger project and I'm getting this error. Clearing node_modules didn't help. React 15.4.2

Error occurs when including just: 

    import AceEditor from 'react-ace';

and when including any of the `brace` components before or after

This is basically a duplicate of https://github.com/securingsincity/react-ace/issues/141 , which was fixed for create-react-app , but doesn't explain what the issue is or how to fix it

**Comment by securingsincity** [comment] 2017-05-20 18:35
@nicholasareed are you still having this issue? can you provide some example code that isn't working?

**Comment by securingsincity** [comment] 2017-05-28 12:45
I'm closing this issue as others have not seen this issue since `4.1.6`. People needed to clear their node_modules folder. It was caused by setting ReactAce to a purecomponent which caused unexpected behavior.

**Closed by securingsincity** 2017-05-28 12:45 UTC
Labels: awaiting response, bug, help wanted
