### ISSUE TITLE
Ctrl-F cannot be used

### ISSUE THREAD

**Issue by ldd010101** [securingsincity/react-ace#178] opened 2017-03-02 07:08 UTC
Ctrl-F lookup cannot be used

**Comment by AlonBe** [comment] 2017-03-02 15:53
Did you had any errors on the console?

Ctrl-F [tries ](https://github.com/ajaxorg/ace/blob/d1a77e9d2c54259f489a96b9f9789d4caa1e52d9/lib/ace/commands/default_commands.js#L183)to load the searchbox extension

Try using: `import 'brace/ext/searchbox';`

**Comment by gillesdemey** [comment] 2017-03-21 21:37
I can confirm that it works when importing `import 'brace/ext/searchbox'`, thanks @AlonBe!

I suggest we close this one?

**Comment by securingsincity** [comment] 2017-03-22 02:35
thanks @AlonBe  and @gillesdemey

**Closed** 2017-03-22 02:35 UTC

**Comment by KurtPreston** [comment] 2017-04-11 15:54
Is there any way to disable the Ctrl-F functionality instead, so the browser's native search can still be used?

**Comment by KurtPreston** [comment] 2017-06-16 14:48
[This StackOverflow post](https://stackoverflow.com/questions/13677898/how-to-disable-ace-editors-find-dialog/27797303#27797303) describes how Ace Editor supports removing the command via

```js
editor.commands.removeCommand('find');
```

Is there a way to do this in react-ace?

**Comment by securingsincity** [comment] 2017-06-16 14:51
https://github.com/securingsincity/react-ace/blob/master/docs/FAQ.md#how-do-call-methods-on-the-editor-how-do-i-call-undo-or-redo explains how to call methods on the editor. also `onLoad`  returns the instance of the editor so you could also do that there.

**Comment by yamyamyuo** [comment] 2019-05-22 08:10
thanks @AlonBe this works for me!

**Comment by hkedia321** [comment] 2019-06-13 17:18
Hi @yamyamyuo @securingsincity, I am trying this, but getting the error: `Uncaught TypeError: _this.requestEditor.removeCommand is not a function`
My code:
```
this.requestEditor = React.createRef()
.......
this.requestEditor.current.editor.removeCommand('find')
.......
<AceEditor
       ref={this.requestEditor}
/>
```
Can someone please help me?
@yamyamyuo If it has worked for you can you please share the syntax?

**Comment by stuartcrobinson** [comment] 2020-06-20 16:35
@hkedia321 this works for me to remove search (ctrl/cmd-f) from react-ace

```

  componentDidMount() {
    this.reactAceComponent.editor.commands.removeCommand('find');
    //...
  }

```
...
```
  <AceEditor
    ref={refs => { this.reactAceComponent = refs }}
    //...
  />
```

**Comment by dadwic** [comment] 2021-01-30 13:05
import "ace-builds/src-noconflict/ext-searchbox";

**Comment by alissoncorsair** [comment] 2024-10-25 15:37
> Hi @yamyamyuo @securingsincity, I am trying this, but getting the error: `Uncaught TypeError: _this.requestEditor.removeCommand is not a function` My code:
> 
> ```
> this.requestEditor = React.createRef()
> .......
> this.requestEditor.current.editor.removeCommand('find')
> .......
> <AceEditor
>        ref={this.requestEditor}
> />
> ```
> 
> Can someone please help me? @yamyamyuo If it has worked for you can you please share the syntax?

For anyone with the same problem, you can access the editor even without using a ref. :)

Example:
```code
<AceEditor
onLoad={(editor) => {
editor.commands.removeCommand("find");
}}
```
