### ISSUE TITLE
Mispelled option for enableAutocompletions

### ISSUE THREAD

**Issue by afang** [securingsincity/react-ace#96] opened 2016-03-27 04:01 UTC
Console is giving an error on the props:

```
misspelled option "enableBasicAutocompletion"
misspelled option "enableLiveAutocompletion"
```

Even though `enableLiveAutocompletion` is set to `{true}`:

```javascript
<AceEditor mode="javascript" theme="tomorrow_night" onChange={this.onChange} name="editor" editorProps={{$blockScrolling: true}} fontSize={14} height="100vh" width="100vw" ref="editor" enableLiveAutocompletion={true}/>
```

**Comment by pgilad** [comment] 2016-03-27 11:05
This seems to be caused by https://github.com/securingsincity/react-ace/commit/f21a6f8e6593530882625ff5a430f12ee58ed204

**Comment by pgilad** [comment] 2016-03-27 11:09
After a little more debugging, you can get rid of the warning by importing:
`import 'brace/ext/language_tools';`

Although this is kinda stupid because there is no need to require it in the first place.

**Comment by afang** [comment] 2016-03-28 00:41
Do I need `Brace` to use Ace.js themes or is it possible to import a custom theme file and set the `<AceEditor theme>` props to match it?

**Comment by chentsulin** [comment] 2016-03-28 02:25
duplicate of #95

**Closed by chentsulin** 2016-03-28 02:25 UTC
