### ISSUE TITLE
Modify value of onChange

### ISSUE THREAD

**Issue by ktalebian** [securingsincity/react-ace#569] opened 2018-11-29 01:52 UTC
I have

```js
<AceEditor
   value={this.state.value}
   onChange=(this.onChange}
>
```

where `onChange` will actually `setState` a different value than what the Editor provides. When I paste some string that does get changed, I get

```
{"message":"Uncaught TypeError: Cannot read property 'substring' of undefined"}
```

Which is coming from https://github.com/thlorenz/brace/blob/master/index.js#L7528. Seems like because I changed the original value, the lines don't match anymore and the application breaks.

This seems like an unexpected behavior since I should be the one controlling the store, and hence the final value of the textarea, and not ReactAce.

**Comment by ganesh-sankey** [comment] 2018-12-12 13:10
I am also getting the same errors

**Comment by securingsincity** [comment] 2018-12-20 02:58
Closing as this is a duplicate of #181  @ktalebian and @ganesh-sankey  there are several solutions listed there.

**Closed by securingsincity** 2018-12-20 02:58 UTC
