### ISSUE TITLE
Console warnings

### ISSUE THREAD

**Issue by VladShcherbin** [securingsincity/react-ace#111] opened 2016-05-26 19:23 UTC
If you don't import `brace/ext/language_tools`, the package will show you warnings:

```console
misspelled option "enableBasicAutocompletion"
misspelled option "enableLiveAutocompletion"
```

**Comment by shepmaster** [comment] 2016-06-25 17:14
Duplicate of #95.

**Closed** 2016-07-08 12:48 UTC
