### ISSUE TITLE
Highlight Active Line Only Works After Deleting A Line

### ISSUE THREAD

**Issue by d4rkb1ue** [securingsincity/react-ace#190] opened 2017-05-05 03:07 UTC
`highlightActiveLine` is opened as default. But it doesn't work at beginning. The highlighter only shows after some editing, for example, delete a whole line. 
This problem can be seen from the `react-ace/example`:

1. At beginning, the first line doesn't highlight.
2. Press `Enter` and then press `Delete`
3. The first line become highlighted.

**Comment by brookshi** [comment] 2017-05-12 10:30
caused by `this.handleMarkers`,
```js
this.handleMarkers(markers || []);
```
may use this code below is a better way
```js
if (markers && markers.length > 0) {
   this.handleMarkers(markers || []);
}
```

**Comment by securingsincity** [comment] 2017-05-13 03:45
@d4rkb1ue this is fixed in `4.2.2` and should work in the example thanks to @brookshi

**Closed by securingsincity** 2017-05-13 03:45 UTC

**Comment by zheeeng** [comment] 2017-06-11 11:22
@securingsincity I met this problem again, if I set markers on AceEditor.
